var L=require("siyuan");async function m(i,r,n){if(!i.saveData)throw new Error("Plugin saveData method is not available");try{await i.saveData(r,n)}catch(t){throw t}}async function u(i,r){if(!i.loadData)return null;try{return await i.loadData(r)||null}catch(n){return null}}async function _(i,r="config.json"){let n=document.documentElement;if(!n)return;let t=n.getAttribute("data-theme-mode")||"light";n.getAttribute("data-asri-palette")==="amber"&&n.removeAttribute("data-asri-palette");let e=await u(i,r);if(e&&e["asri-enhance-amber"]){let a=e["asri-enhance-amber"];typeof a=="boolean"?delete e["asri-enhance-amber"]:(a[t]=!1,e["asri-enhance-amber"]=a),await m(i,r,e)}}async function T(i,r="config.json"){let n=document.documentElement;if(!n)return;n.getAttribute("data-asri-palette")==="amber"&&n.removeAttribute("data-asri-palette");let t=await u(i,r);if(t){let e=Object.keys(t).filter(a=>a.startsWith("asri-enhance-"));e.length>0&&(e.forEach(a=>{delete t[a]}),await m(i,r,t))}}var f="config.json";async function x(i,r){let n=document.documentElement;if(!n)return;let t=n.getAttribute("data-theme-mode")||"light",e=n.getAttribute("data-asri-palette")==="amber",a=await u(i,f)||{},s=a["asri-enhance-amber"]||{light:!1,dark:!1};e?(n.removeAttribute("data-asri-palette"),s[t]=!1,a["asri-enhance-amber"]=s,await m(i,f,a).catch(()=>{})):(n.removeAttribute("data-asri-palette"),n.setAttribute("data-asri-palette","amber"),s[t]=!0,a["asri-enhance-amber"]=s,await m(i,f,a).catch(()=>{}))}async function g(i){let r=document.documentElement;if(!r)return;let n=r.getAttribute("data-theme-mode")||"light",t=await u(i,f);if(t&&t["asri-enhance-amber"]){let e=t["asri-enhance-amber"];(typeof e=="boolean"?e:e[n]===!0)?(r.removeAttribute("data-asri-palette"),r.setAttribute("data-asri-palette","amber")):r.getAttribute("data-asri-palette")==="amber"&&r.removeAttribute("data-asri-palette")}}function H(i,r,n=100){let t,e,a=null,s=0,d=new Set,w=10,C=100,k=()=>{d.forEach(o=>window.clearTimeout(o)),d.clear()},B=(o,b)=>{let l=window.setTimeout(()=>{d.delete(l),o()},b);return d.add(l),l},M=o=>{t!==void 0&&window.clearTimeout(t),t=window.setTimeout(()=>{k();let b=(l=0)=>{var P,y;let v=document.querySelector('#commonMenu[data-name="barmode"] #pickColor');if(v){let h=v.parentElement;if(h){if(!h.querySelector("#asri-enhance-palette")){let c=document.createElement("button");c.className="b3-menu__item asri-enhance",c.id="asri-enhance-palette",c.innerHTML=`
								<svg class="b3-menu__icon" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
									<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
										<path d="M19 3h-4a2 2 0 0 0-2 2v12a4 4 0 0 0 8 0V5a2 2 0 0 0-2-2"></path>
										<path d="m13 7.35l-2-2a2 2 0 0 0-2.828 0L5.344 8.178a2 2 0 0 0 0 2.828l9 9"></path>
										<path d="M7.3 13H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h12m0-4v.01"></path>
									</g>
								</svg>
								<span class="b3-menu__label">${((P=i.i18n)==null?void 0:P.morePresetColors)||"morePresetColors"}</span>
								<svg class="b3-menu__icon b3-menu__icon--small"><use xlink:href="#iconRight"></use></svg>
								<div class="b3-menu__submenu">
									<div class="b3-menu__items">
										<button class="b3-menu__item" id="asri-enhance-amber">
											<svg class="b3-menu__icon" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
												<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
													<path d="M19 3h-4a2 2 0 0 0-2 2v12a4 4 0 0 0 8 0V5a2 2 0 0 0-2-2"></path>
													<path d="m13 7.35l-2-2a2 2 0 0 0-2.828 0L5.344 8.178a2 2 0 0 0 0 2.828l9 9"></path>
													<path d="M7.3 13H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h12m0-4v.01"></path>
												</g>
											</svg>
											<span class="b3-menu__label">${((y=i.i18n)==null?void 0:y.amber)||"amber"}</span>
										</button>
									</div>
								</div>
							`,h.insertBefore(c,v)}let A=h.querySelector("#asri-enhance-amber");A&&(A.onclick=c=>x(i,c))}r(o);return}l+1<w?B(()=>b(l+1),C):r(o)};b(),t=void 0},n)},E=()=>{let o=document.querySelector("#barMode");if(o){a=o,o.addEventListener("click",M,!0),e=void 0;return}s+=1,s<w?e=window.setTimeout(E,C):e=void 0};return E(),()=>{e!==void 0&&(window.clearTimeout(e),e=void 0),k(),a&&(a.removeEventListener("click",M,!0),a=null),t!==void 0&&(window.clearTimeout(t),t=void 0)}}var p=class extends L.Plugin{constructor(){super(...arguments);this.unsubscribeBarModeClick=null;this.asriConfigClickHandler=null;this.themeModeObserver=null}async onload(){this.unsubscribeBarModeClick=H(this,()=>{}),this.asriConfigClickHandler=t=>{let e=t.target;if(!e||e.closest("#asri-enhance-amber"))return;let a=e.closest(".asri-config");a&&a.id!=="topbarFusionPlus"&&_(this,"config.json").catch(()=>{})},document.addEventListener("click",this.asriConfigClickHandler,!0);let n=document.documentElement;n&&(this.themeModeObserver=new MutationObserver(t=>{for(let e of t)e.type==="attributes"&&e.attributeName==="data-theme-mode"&&g(this).catch(()=>{})}),this.themeModeObserver.observe(n,{attributes:!0,attributeFilter:["data-theme-mode"]})),setTimeout(()=>{g(this).catch(()=>{})},500)}onunload(){this.unsubscribeBarModeClick&&(this.unsubscribeBarModeClick(),this.unsubscribeBarModeClick=null),this.asriConfigClickHandler&&(document.removeEventListener("click",this.asriConfigClickHandler,!0),this.asriConfigClickHandler=null),this.themeModeObserver&&(this.themeModeObserver.disconnect(),this.themeModeObserver=null)}async uninstall(){this.onunload(),await T(this,"config.json").catch(()=>{})}};module.exports=p;
